import { ColorScheme } from "@/hooks/useColorScheme";
import { StyleSheet } from "react-native";

export const createHomeStyles = (colors:ColorScheme)=>{
    const styles = StyleSheet.create({
        container:{
            flex:1
        },
        safeArea:{
            flex:1
        },
        loadingContainer:{
            flex:1,
            justifyContent:"center",
            alignItems:'center'
        },
        loadingText:{
            marginTop:20,
            fontSize:18,
            fontWeight:"500",
            color:colors.text
        },
        header:{
            paddingHorizontal:24,
            paddingVertical:32,
            paddingBottom:24
        },
        titleContainer:{
            flexDirection:"row",
            alignItems:'center',
            marginBottom:20
        },
        iconContainer:{
            width:56,
            height:56,
            borderRadius:16,
            justifyContent:'center',
            alignItems:'center',
            marginRight:16
        },
        titleTextContainer:{
            flex:1
        },
        title:{
            fontSize:32,
            fontWeight:'700',
            letterSpacing:-1,
            marginBottom:4,
            color:colors.text
        },
        subtitle:{
            fontSize:17,
            fontWeight:'500',
            color:colors.textMuted,

        },
        progressContainer:{
            marginTop:8
        },
        progressBarContainer:{
            flexDirection:'row',
            alignItems:'center',
            gap:16
        },
        progressBar:{
            flex:1,
            height:12,
            borderRadius:6,
            overflow:'hidden',
            backgroundColor:colors.border
        },
        progressFill:{
            height:"100%",
            borderRadius:6
        },
        progressText:{
            fontSize:16,
            fontWeight:"700",
            minWidth:40,
            textAlign:'right',
            color:colors.success
        },
        inputSection:{
            paddingHorizontal:24,
            paddingBottom:12
        },
        inputWrapper:{
            flexDirection:'row',
            alignItems:'flex-end',
            gap:16
        },
        input:{
            flex:1,
            borderWidth:2,
            borderRadius:20,
            paddingHorizontal:20,
            paddingVertical:16,
            fontSize:17,
            maxHeight:120,
            fontWeight:"500",
            backgroundColor:colors.backgrounds.input,
            borderColor:colors.border,
            color:colors.text
        }
    })
}